const prisma = require('../config/database');

// Create a new Channel
const createChannel = async (req, res) => {
    try {
        const { name, workspaceId } = req.body;

        // Ensure the workspace exists
        const workspace = await prisma.workspace.findUnique({
            where: { id: parseInt(workspaceId) }
        });

        if (!workspace) {
            return res.status(404).json({ error: "Workspace not found" });
        }

        // Create channel (inviteCode is auto-generated by DB default)
        const channel = await prisma.channel.create({
            data: {
                name,
                workspaceId: parseInt(workspaceId)
            }
        });

        res.status(201).json(channel);
    } catch (error) {
        // Handle unique constraint violation (duplicate channel name in same workspace)
        if (error.code === 'P2002') {
            return res.status(400).json({ error: "Channel name already exists in this workspace" });
        }
        console.error("Create Channel Error:", error);
        res.status(500).json({ error: "Failed to create channel" });
    }
};

// Join a Channel via Invite Code
const joinChannel = async (req, res) => {
    try {
        const { inviteCode } = req.body;
        const userId = req.user.userId;

        // Find channel by code
        const channel = await prisma.channel.findUnique({
            where: { inviteCode },
            include: { workspace: true }
        });

        if (!channel) {
            return res.status(404).json({ error: "Invalid invite code" });
        }

        // Check if user is already a member of the workspace
        const existingMember = await prisma.workspaceMember.findUnique({
            where: {
                userId_workspaceId: {
                    userId,
                    workspaceId: channel.workspaceId
                }
            }
        });

        if (existingMember) {
            return res.status(200).json({
                message: "You are already a member of this workspace",
                channel
            });
        }

        // Add user to the workspace
        await prisma.workspaceMember.create({
            data: {
                userId,
                workspaceId: channel.workspaceId,
                role: 'MEMBER'
            }
        });

        res.status(200).json({
            message: "Successfully joined workspace via channel code",
            channel
        });

    } catch (error) {
        console.error("Join Channel Error:", error);
        res.status(500).json({ error: "Failed to join channel" });
    }
};

// Get all channels for a workspace
const getChannels = async (req, res) => {
    try {
        const { workspaceId } = req.params;

        const channels = await prisma.channel.findMany({
            where: { workspaceId: parseInt(workspaceId) },
            orderBy: { createdAt: 'asc' }
        });

        res.json(channels);
    } catch (error) {
        console.error("Get Channels Error:", error);
        res.status(500).json({ error: "Failed to fetch channels" });
    }
};

// Update a channel name
const updateChannel = async (req, res) => {
    try {
        const { channelId } = req.params;
        const { name } = req.body;

        if (!name || name.trim().length === 0) {
            return res.status(400).json({ error: "Channel name is required" });
        }

        const channel = await prisma.channel.update({
            where: { id: parseInt(channelId) },
            data: { name: name.trim().toLowerCase().replace(/\s+/g, '-') }
        });

        res.json(channel);
    } catch (error) {
        if (error.code === 'P2002') {
            return res.status(400).json({ error: "Channel name already exists in this workspace" });
        }
        if (error.code === 'P2025') {
            return res.status(404).json({ error: "Channel not found" });
        }
        console.error("Update Channel Error:", error);
        res.status(500).json({ error: "Failed to update channel" });
    }
};

// Delete a channel
const deleteChannel = async (req, res) => {
    try {
        const { channelId } = req.params;

        // First delete all messages in this channel
        await prisma.message.deleteMany({
            where: { channelId: parseInt(channelId) }
        });

        // Then delete the channel
        await prisma.channel.delete({
            where: { id: parseInt(channelId) }
        });

        res.json({ message: "Channel deleted successfully" });
    } catch (error) {
        if (error.code === 'P2025') {
            return res.status(404).json({ error: "Channel not found" });
        }
        console.error("Delete Channel Error:", error);
        res.status(500).json({ error: "Failed to delete channel" });
    }
};

module.exports = {
    createChannel,
    joinChannel,
    getChannels,
    updateChannel,
    deleteChannel
};